name: Deploy NestJS to VPS via SSH and Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy to VPS over SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}  # Адрес твоего сервера
        username: ${{ secrets.USERNAME }}  # Имя пользователя
        key: ${{ secrets.PRIVATE_KEY }}  # Приватный SSH ключ
        script: |
          cd /var/www/vkr/api
          
          # Если репозиторий уже клонирован, делаем pull
          git pull || git clone https://github.com/ElamanBaiguanishev/corporate-social-network-backend .

          # Строим Docker-образ
          docker build -t nest-api .

          # Останавливаем и удаляем старый контейнер (если есть)
          docker stop nest-api || true
          docker rm nest-api || true

          # Запускаем новый контейнер, передавая переменные окружения
          docker run -d \
            --name nest-api \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -p 3000:3000 \
            nest-api
